apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goalixa-pwa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/goalixa/goalixa-pwa.git
    targetRevision: main
    path: helm
    helm:
      parameters:
        - name: image.tag
          value: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: goalixa-pwa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
