image:
  registry: harbor.goalixa.com
  repository: pwa-staging/pwa
  tag: "latest"
  pullPolicy: Always
  pullSecret: harbor-pull

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: "staging.goalixa.com"
  tlsSecret: "staging-goalixa-pwa-tls"
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

namespace:
  name: pwa-staging