image:
  registry: harbor.goalixa.com
  repository: goalixa-pwa/pwa
  tag: "latest"
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: "app.goalixa.com"
  tlsSecret: "app-goalixa-tls"
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

namespace:
  name: goalixa-pwa
