image:
  registry: harbor.goalixa.com
  repository: pwa-staging/pwa
  tag: "latest"
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: "staging.goalixa.com"
  tlsSecret: "staging-goalixa-pwa-tls"
  tls: true

namespace:
  name: pwa-staging